name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: muzammil-viabletree/utils-docs@main # This is the action
        with:
          heroku_api_key: "1781e6cf-3a55-4f4e-a7c2-54868599a6e7"
          heroku_app_name: "utils-docs" #Must be unique in Heroku
          heroku_email: "muhammad.muzammil@viabletree.com"